- packages/mds-compliance/api.ts
- packages/mds-providers/index.ts
The provider has been transitioned to a new provider_id value.
> Remove deprecated provider_id value

- bin/mdsctl
- packages/mds-daily/request-handlers.ts
- packages/mds-daily/tests/request-handlers.test.ts
- packages/mds-utils/tests/utils.spec.ts
- packages/mds-utils/utils.ts
Migrated from https://github.com/CityOfLosAngeles/mds-core/pull/201
> [mds-daily] Add `undefined` handling to getVehicleCounts()

- packages/mds-compliance/api.ts
- packages/mds-db/tests/mds-db.spec.ts
> [mds-compliance] [mds-db] Resolve Geography build errors.

- packages/mds-agency/tests/request-handlers.ts
- packages/mds-types/index.ts
Slack discussion https://lacuna-tech.slack.com/archives/CHXQXQK5M/p1571325224046400
I did a project-wide find for `'car'` and this was the fruit of that search. Please let me know if MDSAAS-277 entails more/less than this.
> [mds-agency] s/car/carshare/g MDSAAS-277

- packages/mds-cache/index.ts
> [mds-cache] Remove unused cache methods.

- helm/mds/requirements.lock
- helm/mds/requirements.yaml
- helm/mds/templates/egress.yaml
- helm/mds/values.yaml
- helm/util/values.yaml
verify:
util logs
```
% ./bin/mdsctl install:logging
% kubectl logs -n util elasticsearch-master-0
% kubectl logs -n util logging-fluentbit-<tab>
% kubectl logs -n util logging-kibana-<tab>
```
kibana
```
% ./bin/mdsctl -p minimal install:mds
% MDS_SIMULATOR_REPOSITORY=[REPO] ./bin/mdsctl install:simulator
% ./bin/mdsctl open:kibana
```
issues:
- ~there is a mds-fluent-bid pod running in the mds namespace at present~
> fluentbit (mds/requirements rm, util/values pin to es host)

- packages/mds-daily/api.ts
- packages/mds-daily/db-helpers.ts
- packages/mds-daily/request-handlers.ts
> [mds-daily] Add perf logging to MDS Daily db/cache calls

- packages/mds-compliance/package.json
- packages/mds-compliance/tsconfig.build.json
- packages/mds-db/events.ts
- packages/mds-db/index.ts
- packages/mds-db/trips.ts
> [mds-db] [mds-compliance] pull changes from fix/michael/remove-provider-api

- packages/mds-daily/request-handlers.ts
> [mds-daily] Resolve lint errors

- packages/mds-api-server/index.ts
API logs will contain the provider ID to assist in troubleshooting.
```
INFO 5674ea42-a2ab-42e0-b9fd-cbade6cb2561 GET /audit 200 96 - 4.014 ms
```
> Add provider_id to API logs

- package.json
Exclude downloaded helm charts from being cleaned by yarn
> please leave downloaded helm charts in place

- packages/mds-daily/api.ts
- packages/mds-daily/request-handlers.ts
> [mds-daily] Break up last day stats by provider endpoint

- packages/mds-agency/tests/request-handlers.ts
- packages/mds-types/index.ts
> [mds-*] Rename carshare back to car to match spec properly

- bin/mdsctl
small patch to support mds port consolidation to 4000
> simulator needs to access mds-agency:4000 vs 4001

- README.md
- cypress/integration/agency.spec.js
Some additions to the onboarding docs, and making kubernetes/docker integration tests a little less specific so they should pass for anyone if everything is working.
No code impact.
> [mds-core] Onboarding Improvements

- packages/mds-metrics/request-handlers.ts
> [mds-metrics] Add some more logs for the Metrics API prototype

- container-images/mds-agency/Dockerfile
> remove psql-client

- packages/mds-db/index.ts
- packages/mds-db/processors.ts
- packages/mds-db/tests/mds-db.spec.ts
- packages/mds-metrics/api.ts
- packages/mds-metrics/request-handlers.ts
- packages/mds-metrics/tests/request-handlers.test.ts
- packages/mds-metrics/types.ts
🚨**Do not merge before #88**🚨
I have yet to run this against the database, so my SQL may have some issues.
Note: I targeted Evan's fork for this to make reviewing easier, but really it ought to point to develop.
> [WIP] [mds-metrics] Add dump all metrics rows API endpoint

- packages/mds-api-authorizer/index.ts
- packages/mds-api-server/index.ts
> Minor authorizer refactor

- packages/mds-types/index.ts
> [mds-*] Add moped to VEHICLE_TYPES enum

- packages/mds-cache/index.ts
Fixes a build error introduced in 8a20a81.
> [mds-cache] Fix build error

- .vscode/settings.json
> Update VS Code ESLint settings

- packages/mds-db/client.ts
- packages/mds-db/devices.ts
- packages/mds-db/events.ts
- packages/mds-db/telemetry.ts
- packages/mds-db/trips.ts
> [mds-db] Refactor makeReadOnlyQuery to permit use of SqlVals()

- packages/mds-agency/request-handlers.ts
> [mds-agency] Fix import of package with no default export

- packages/mds-web-sockets/clients.ts
> [mds-web-sockets] Check for admin:all scope when authenticating clients

- container-images/mds-web-sockets/package.json
> Fix image name for mds-web-sockets

- container-images/mds-web-sockets/package.json
- packages/mds-web-sockets/launch_server.ts
- packages/mds-web-sockets/package.json
- packages/mds-web-sockets/server.ts
> [mds-web-sockets] Don't always start WebSocket server

- packages/mds-event-processor/tsconfig.build.json
- packages/mds-provider-processor/package.json
- packages/mds-provider-processor/tests/metrics.test.ts
- packages/mds-provider-processor/tsconfig.build.json
- packages/mds-trip-processor/tsconfig.build.json
> [mds-provider-processor] A few unit tests for mds-provider-processor.

- packages/mds-web-sockets/server.ts
Because PING messages are handled by the wsHeartbeat package, we can just ignore them in our manual handler.
> [mds-web-sockets] Fix PING message handling

- bin/mdsctl
> [mds-*] Append commit hash to image tag if on non-master branch

- packages/mds-metrics-sheet/metrics-log.ts
- packages/mds-metrics-sheet/utils.ts
- packages/mds-metrics-sheet/vehicle-counts.ts
> Extend daily timeout

- packages/mds-audit/attachments.ts
make sure we have AWS env vars before we make the call asking for AWS creds
> [mds-audit] speed up unit tests

- packages/mds-policy-author/request-handlers.ts
- packages/mds-policy-author/tests/api.spec.ts
> two changes to fix heisenbug pt 2 in policy-author

- packages/mds-utils/date-time-utils.ts
- packages/mds-utils/tests/date-time-utils.spec.ts
- packages/mds-utils/tests/utils.spec.ts
- packages/mds-utils/utils.ts
See https://github.com/moment/moment/issues/955
Fix is to add `.clone()` before datetime math.
> Don't mutate datetime

- okteto.yml
> [mds-*] Bump okteto resources massively to avoid crashes at debug init

- packages/mds-policy/tests/api.spec.ts
The intermittent policy test failure (result undefined) as reported was actually hiding the following underlying error: 
```
@mds-core/mds-policy: result was undefined. err was Error: ECONNRESET: Connection reset by peer
```
I think this is potentially due to the mix of async and callback style tests where the `supertest` server was occasionally being torn down before one of the test callbacks was complete.
I converted all tests to the async style so they are consistent in the hopes that this will resolve the issue.
> Make all tests async

- packages/mds-db/index.ts
> [mds-db] Refactor en-mass import/exports in mds-db to be more readable

- packages/mds-db/processors.ts
- packages/mds-db/trips.ts
> [mds-db] Fix build error by exporting interfaces

- packages/mds-api-server/index.ts
- packages/mds-api-server/tests/index.spec.ts
- packages/mds-native/api.ts
- packages/mds-native/tests/api.spec.ts
- packages/mds-native/types.ts
Middleware to support API version negotiation as documented in MDS Provider [spec](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev/provider#versioning)
> OMF-26 API Version Middleware

- packages/mds-web-sockets/README.md
> [docs] Add docs for mds-web-sockets

- packages/mds-stream/index.ts
> [mds-stream] Swallow STAN fatal errors. Previously, these would cause a node crash dump.

- packages/mds-cache/index.ts
> [mds-cache] Fix Multi definition in mds-cache

- packages/mds-jurisdiction-service/index.ts
Catch errors connecting to DB separately to control the exception type
> Catch db connection errors separately

- packages/mds-web-sockets/clients.ts
- packages/mds-web-sockets/tests/test.ts
> [mds-web-sockets] Add structured response for authentication success and failure

- packages/mds-agency/request-handlers.ts
- packages/mds-schema-validators/tests/validators.spec.ts
- packages/mds-schema-validators/validators.ts
See LCORE-95 for more context. Validation errors from Joi are not bubbled down to the consumer, and are instead logged.
> [mds-agency] [mds-utils] Add better object validation to agency.

- .vscode/launch.json
- packages/mds-jurisdiction-service/index.ts
- packages/mds-jurisdiction-service/orm.ts
- packages/mds-jurisdiction-service/tests/index.spec.ts
- packages/mds-jurisdiction/api.ts
- packages/mds-jurisdiction/handlers/delete-jurisdiction.ts
- packages/mds-jurisdiction/handlers/index.ts
- packages/mds-jurisdiction/handlers/update-jurisdiction.ts
- packages/mds-jurisdiction/tests/api.spec.ts
- packages/mds-orm/types.ts
- packages/mds-schema-validators/validators.ts
> Endpoints to update/delete a jurisdiction

- packages/mds-agency/request-handlers.ts
> [mds-agency] Reorder writing an event and related telemetry to avoid race condition where event is written but telemetry has not been written yet

- bin/mdsctl
- container-images/mds-geography/Dockerfile
- container-images/mds-geography/index.ts
- container-images/mds-geography/package.json
- container-images/mds-geography/tsconfig.build.json
- container-images/mds-geography/webpack.config.js
- helm/mds/values.yaml
- packages/mds-geography-author/api.ts
- packages/mds-geography/LICENSE
- packages/mds-geography/README.md
- packages/mds-geography/api.ts
- packages/mds-geography/index.ts
- packages/mds-geography/package.json
- packages/mds-geography/server.ts
- packages/mds-geography/tests/api.spec.ts
- packages/mds-geography/tsconfig.build.json
- packages/mds-policy/api.ts
- packages/mds-policy/tests/api.spec.ts
> [mds-policy] [mds-geography] Extract read-only geography service from policy service

- packages/mds-geography/package.json
- packages/mds-policy-author/api.ts
- packages/mds-policy-author/request-handlers.ts
- packages/mds-policy-author/tests/request-handlers.test.ts
- packages/mds-policy/tests/api.spec.ts
- packages/mds-types/index.ts
> [mds-policy-author] Minor changes to policy to bring it back in line with the spec.

- packages/mds-agency/request-handlers.ts
- packages/mds-agency/tests/integration-tests.ts
- packages/mds-agency/types.ts
- packages/mds-agency/utils.ts
> [mds-agency] Fix event type for vehicle reads in case of a cache miss

- packages/mds-utils/date-time-utils.ts
> [mds-utils] Update relative time parsing to snap to the nearest hour when 'now' is provided as a query param

- container-images/mds-event-processor/index.ts
- container-images/mds-event-processor/package.json
- container-images/mds-event-processor/tsconfig.build.json
- packages/mds-stream-processor/index.ts
- packages/mds-stream-processor/labelers/device-labeler.ts
- packages/mds-stream-processor/labelers/geography-labeler.ts
- packages/mds-stream-processor/labelers/index.ts
- packages/mds-stream-processor/labelers/latency-labeler.ts
- packages/mds-stream-processor/labelers/types.ts
- packages/mds-stream-processor/package.json
- packages/mds-stream-processor/processors/mds-event-processor.ts
- packages/mds-stream-processor/server.ts
- packages/mds-stream-processor/tsconfig.build.json
> Add caching of device labels

- packages/mds-stream-processor/processors/vehicle-event-processor.ts
- packages/mds-stream/kafka/agency-stream-kafka.ts
- yarn.lock
> [mds-stream] [mds-stream-processor] TENANT_ID prefix for Kafka Streams

- packages/mds-stream-processor/connectors/console-connector.ts
- packages/mds-stream-processor/connectors/generator-connector.ts
- packages/mds-stream-processor/connectors/kafka-connector.ts
- packages/mds-stream-processor/processors/index.ts
- packages/mds-stream-processor/processors/vehicle-event-processor.ts
Added some additional examples that may prove useful for testing... For example:
```ts
StreamTap(
GeneratorSource(function* numbers() {
for (let i = 0; i < 10; i++) {
yield i
}
}),
ConsoleSink()
).start()
```
Produces the following console output:
```
INFO 1
INFO 2
INFO 3
INFO 4
INFO 5
INFO 6
INFO 7
INFO 8
INFO 9
```
> Add some source/sink examples

- packages/mds-agency/request-handlers.ts
> [mds-agency] Re-add stream init that was removed, thanx git

- package.json
- packages/mds-stream-processor/connectors/file-connector.ts
- packages/mds-stream-processor/package.json
- yarn.lock
> [mds-stream-processors] Add FileSource and FileSync connectors for mds-stream-processors

- bin/mdsctl
- helm/mds/templates/auth.yaml
- helm/mds/templates/ingress.yaml
- helm/mds/tests/service-all-disabled_test.yaml
- helm/mds/values.yaml
> [helm] Update helm for telemetry processor

- packages/mds-db/telemetry.ts
- packages/mds-utils/utils.ts
> [mds-utils] Remove dependency on mds-db

- packages/mds-compliance/tests/api.spec.ts
- packages/mds-test-data/test-areas/council-district-11.ts
- packages/mds-test-data/test-areas/la-city-boundary.ts
- packages/mds-test-data/test-areas/la-dacs.ts
- packages/mds-test-data/test-areas/non-san-fernando-dac.ts
- packages/mds-test-data/test-areas/restricted-areas.ts
- packages/mds-test-data/test-areas/san-fernando-dac.ts
- packages/mds-test-data/test-areas/service-area-new.ts
- packages/mds-test-data/test-areas/service-area-old.ts
- packages/mds-test-data/test-areas/service-areas.ts
- packages/mds-test-data/test-areas/test-areas.ts
- packages/mds-test-data/test-areas/venice-special-ops-zone.ts
- packages/mds-test-data/test-areas/venice.ts
Long term solution is to clean a lot of this stuff up or remove. For now, this allows the test areas to be packaged properly.
> Convert test data to TS

- container-images/mds-agency/webpack.config.ts
- container-images/mds-audit/webpack.config.ts
- container-images/mds-compliance/webpack.config.ts
- container-images/mds-daily/webpack.config.ts
- container-images/mds-event-processor/webpack.config.ts
- container-images/mds-geography-author/webpack.config.ts
- container-images/mds-geography/webpack.config.ts
- container-images/mds-jurisdiction/webpack.config.ts
- container-images/mds-metrics-sheet/webpack.config.ts
- container-images/mds-policy-author/webpack.config.ts
- container-images/mds-policy/webpack.config.ts
- container-images/mds-telemetry-processor/webpack.config.ts
- container-images/mds-web-sockets/webpack.config.ts
- packages/mds-api-server/index.ts
- packages/mds-webpack-config/index.ts
- More expressive type for API query parameters
- Use builder pattern for webpack configuration to simplify syntax
> API Request Query and Webpack Configuration enhancements

- bin/mdsctl
allows extension pass-through
test:
- see https://github.com/lacuna-tech/mds-core/pull/271
> +invokeAny

- packages/mds-repository/entities/identity-entity.ts
> Remove extra @Column decorator

- packages/mds-daily/request-handlers.ts
- packages/mds-jurisdiction-service/service/repository/index.ts
- packages/mds-stream/kafka/stream-consumer.ts
- packages/mds-stream/kafka/stream-producer.ts
- packages/mds-utils/tests/utils.spec.ts
- packages/mds-utils/utils.ts
> [mds-utils] FilterEmptyHelper rework

- packages/mds-agency/request-handlers.ts
> [mds-agency] Fix PUT agency/vehicles error handling on failed cache/stream write

- packages/mds-webpack-config/index.ts
> [mds-webpack-config] Do not ignore ioredis at bundle-time

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
The `Impacts` list in the PR template is out of date.
> Fix PR Template

- packages/mds-geography-author/api.ts
- packages/mds-stream/kafka/stream-producer.ts
- tsconfig.json
Quick patch to resolve build issue that got through CI, as well as downgrading to ES2019 from ES2020 due to webpack build issues.
mds-geography-author
> 🐛[mds-geography-author] Add missing data wrapper in geography-author that somehow got through CI/CD, ES2020->ES2019 downgrade

- bin/mdsctl
patch helm initialization such that tiller works
something changed last week that impacted a number of folks, to which this patch is the prescribed/suggested remedy
this patch works, as is, in lacuna-data and maxj's branch of lacuna-mds
bin/mdsctl
> patch helm-init issue

- helm/mds/requirements.lock
- helm/mds/requirements.yaml
Update helm chart versions for redis and postgresql
> bump versions

- packages/mds-stream/index.ts
- packages/mds-stream/package.json
- packages/mds-stream/test-utils.ts
- packages/mds-stream/tests/mock-stream.test.ts
- packages/mds-stream/types.ts
Add a utility to mock stream interfaces.
*[mds-stream]*
Do I need to explicitly export the `WriteStream` type in `index.ts`?
Do I need to explicitly add `sinon` to deps?
> Add mockStream() util

- packages/mds-compliance/api.ts
- packages/mds-compliance/constants.ts
- packages/mds-compliance/helpers.ts
- packages/mds-compliance/mds-compliance-cli.ts
- packages/mds-compliance/mds-compliance-engine.ts
- packages/mds-compliance/tests/engine-test.spec.ts
I need to do some other compliance-related work, and I couldn't figure out how to do it without doing a closer reading of the compliance code. I thought future developers could benefit from me noting the code with some comments and some renaming to improve code comprehension.
[] No functionality added.
[mds-compliance]
> Refactoring and commenting compliance code.

- packages/mds-agency/api.ts
- packages/mds-audit/api.ts
- packages/mds-compliance/api.ts
- packages/mds-daily/api.ts
- packages/mds-policy/api.ts
Missed a commit in a previous PR. The checks for `'/'` are no longer necessary.
> Remove some unecessary path checks

- packages/mds-compliance/index.ts
I want to be able to make use of the compliance engine methods directly, rather than making calls through the compliance API, for the compliance metrics script reboot.
*[list of packages]*
> [mds-compliance] Expose compliance engine functions

- packages/mds-agency-cache/index.ts
A bug was identified when perusing our k8s logs where we were failing to write the telemetry to the proper key. This fixes that!
mds-agency-cache
mds-agency
> [mds-agency-cache] [mds-agency] Fix un-decorated telemetry write that would fail for all of eternity

- packages/mds-compliance/mds-compliance-engine.ts
- packages/mds-compliance/test_data/policies.json
- packages/mds-compliance/tests/api.spec.ts
- packages/mds-compliance/tests/engine-test.spec.ts
- packages/mds-types/index.ts
- packages/mds-utils/utils.ts
A bug was identified in the evaluation of time rules in compliance, where we were doing improper unit conversion. This resolves that.
mds-compliance
> [mds-compliance] Fix time rule compliance evaluation and tests

- packages/mds-jurisdiction-service/service/repository/index.ts
- packages/mds-repository/exceptions.ts
- packages/mds-service-helpers/server/index.ts
We run ProcessManager as part of our unit tests for services. When terminating the service a process.exit() was being called which effectively shut down mocha causing tests to either fail, or errors not be reported.
> Fix issue with unit tests not being run or errors not being reported

- packages/mds-api-server/index.ts
- yarn.lock
Make middleware available via exports
> Export prometheus and compression middleware

- packages/mds-api-helpers/package.json
- packages/mds-api-helpers/tests/index.spec.ts
Adds complete unit tests for parseRequest
[mds-api-helpers]
> [mds-api-helpers] Add tests for parseRequest

- packages/mds-agency-cache/index.ts
- packages/mds-agency-cache/types.ts
- packages/mds-agency-cache/unflatteners.ts
- packages/mds-agency/request-handlers.ts
- packages/mds-agency/tests/integration-tests.spec.ts
- packages/mds-agency/types.ts
- packages/mds-agency/utils.ts
- packages/mds-audit/api.ts
- packages/mds-audit/service.ts
- packages/mds-audit/tests/api.spec.ts
- packages/mds-compliance/helpers.ts
- packages/mds-daily/request-handlers.ts
- packages/mds-db/tests/mds-db.spec.ts
- packages/mds-schema-validators/tests/validators.spec.ts
- packages/mds-schema-validators/validators.ts
- packages/mds-test-data/index.ts
- packages/mds-types/index.ts
- packages/mds-utils/state-machine.ts
- packages/mds-utils/tests/utils.spec.ts
Gets mds-agency successfully passing preexisting tests. This does *not* add additional tests to cover new use-cases for 1.0 yet. 
Please take a careful look at this, especially the changes to the test suite itself. There are a few places where I had to do some pretty janky stuff (mostly around extracting request body for writing vehicle events), if you have clean suggestions please post them :)
[mds-agency]
[mds-agency-cache]
> [mds-agency] [mds-agency-cache] 1.0.0 Agency Tests Passing

- packages/mds-agency-cache/index.ts
- packages/mds-agency-cache/types.ts
- packages/mds-agency-cache/unflatteners.ts
- packages/mds-agency/request-handlers.ts
- packages/mds-agency/tests/integration-tests.spec.ts
- packages/mds-agency/types.ts
- packages/mds-agency/utils.ts
- packages/mds-audit/api.ts
- packages/mds-audit/service.ts
- packages/mds-audit/tests/api.spec.ts
- packages/mds-compliance/helpers.ts
- packages/mds-daily/request-handlers.ts
- packages/mds-db/tests/mds-db.spec.ts
- packages/mds-schema-validators/tests/validators.spec.ts
- packages/mds-schema-validators/validators.ts
- packages/mds-test-data/index.ts
- packages/mds-types/index.ts
- packages/mds-utils/state-machine.ts
- packages/mds-utils/tests/utils.spec.ts
Reverts lacuna-tech/mds-core#401
> Revert "[mds-agency] [mds-agency-cache] 1.0.0 Agency Tests Passing"

- helm/mds/templates/deployment.yaml
- package.json
- packages/mds-agency/package.json
- packages/mds-agency/tsconfig.build.json
- packages/mds-db/tsconfig.build.json
- packages/mds-jurisdiction-service/@types/index.ts
- packages/mds-jurisdiction-service/client/index.ts
- packages/mds-jurisdiction-service/package.json
- packages/mds-jurisdiction-service/server/index.ts
- packages/mds-jurisdiction-service/server/manager.ts
- packages/mds-jurisdiction-service/tests/index.spec.ts
- packages/mds-jurisdiction-service/tsconfig.build.json
- packages/mds-jurisdiction/tests/api.spec.ts
- packages/mds-policy/tsconfig.build.json
- packages/mds-rpc-common/@types/index.ts
- packages/mds-rpc-common/client/index.ts
- packages/mds-rpc-common/docs/rpc-architecture.puml
- packages/mds-rpc-common/index.ts
- packages/mds-rpc-common/package.json
- packages/mds-rpc-common/server/index.ts
- packages/mds-rpc-common/tests/index.spec.ts
- packages/mds-rpc-common/tsconfig.build.json
- packages/mds-rpc-common/tsconfig.eslint.json
- tsconfig.build.json
- tsconfig.json
- yarn.lock
Contribute RPC common module and convert jurisdiction service/API to RPC. 
Also, fix some missing dependencies and project references.
> RPC Jurisdiction Service

- .gitignore
- .npmrc
- Jenkinsfile
- README.md
Add a Jenkinsfile for running build/test of PR branches
> Jenkinsfile

- packages/mds-repository/repository.ts
- packages/mds-service-helpers/server/index.ts
Remove repetitive process monitor log.
Add schema version (most recent migration) log.
> Very minor logging changes

- helm/mds/templates/deployment.yaml
Keep KAFKA/NATS env vars from showing up when not needed
> add enable/disable toggle for kafka/nats

- package.json
- packages/mds-agency-cache/index.ts
- packages/mds-agency/tests/integration-tests.spec.ts
- packages/mds-policy-author/tests/api.spec.ts
- packages/mds-policy-author/types.ts
- yarn.lock
Upgrades us from TS 3.8 -> TS 4.0!
Everything
> Upgrade to TS 4.0

- packages/mds-api-server/@types/index.ts
Export a type for defining `res.locals.version`
> Add ApiResponseLocalsVersion type

- packages/mds-agency-cache/types.ts
- packages/mds-agency-cache/unflatteners.ts
- packages/mds-compliance/api.ts
- packages/mds-compliance/test_data/low_limit_policy.json
- packages/mds-compliance/test_data/policies.json
- packages/mds-compliance/tests/api.spec.ts
- packages/mds-compliance/tests/engine-test.spec.ts
- packages/mds-utils/utils.ts
This includes this branch: https://github.com/lacuna-tech/mds-core/pull/404
Anyway, the compliance tests were broken on `dev/upgrade-to-1.0`. To get them working again, I had to merge in Neil's branch, and change the fixtures.
> Get compliance tests running again

- .iyarc
Exclude advisory https://npmjs.com/advisories/1561
> Exlude vulnerability advisory

- packages/mds-rpc-common/client/index.ts
- packages/mds-rpc-common/package.json
- packages/mds-rpc-common/server/index.ts
- yarn.lock
Simplify the port assignment logic to resolve the `Starting RPC server listening for application/grpc-web+json requests on port undefined` issue.
> Cleanup RPC host/port assignments

- packages/mds-db/migration.ts
- packages/mds-db/package.json
- packages/mds-db/schema.ts
- packages/mds-db/tests/mds-db.spec.ts
- packages/mds-db/tests/migration.spec.ts
- packages/mds-db/tsconfig.build.json
- packages/mds-geography-service/index.ts
- packages/mds-policy-service/index.ts
*[description/approach]*
*[list of packages]*
> Use repo to create tables for mds-db tests

- container-images/mds-ingest-service/Dockerfile
- container-images/mds-ingest-service/package.json
- container-images/mds-ingest-service/tsconfig.eslint.json
- container-images/mds-ingest-service/webpack.config.ts
> [mds-ingest-service] Add mds-ingest-service container image

- packages/mds-attachment-service/repository/migrations/1603203608358-CreateAttachmentsTable.ts
- packages/mds-audit-service/repository/migrations/1603220489874-CreateAuditsTable.ts
- packages/mds-audit-service/repository/migrations/1603226483200-CreateAuditEventsTable.ts
- packages/mds-audit-service/repository/migrations/1603247961047-CreateAuditAttachmentsTable.ts
- packages/mds-ingest-service/repository/migrations/1603212409274-CreateDevicesTable.ts
- packages/mds-ingest-service/repository/migrations/1603212540962-CreateEventsTable.ts
- packages/mds-ingest-service/repository/migrations/1603212619514-CreateTelemetryTable.ts
Adding default to existing tables for consistency.
> Add DEFAULT to recorded column for existing tables

- helm/mds/values.yaml.tpl
> [helm] Update entry for audit service

- helm/mds/values.yaml.tpl
- packages/mds-ingest-service/client/index.ts
- packages/mds-ingest-service/service/manager.ts
The MDS prefix on the ingest service was resulting in issues with some of our templates. This fixes that.
- mds-ingest-service
> [helm] [mds-ingest-service] Remove MDS prefix from env vars for Ingest Service

- packages/mds-attachment-service/package.json
- packages/mds-attachment-service/service/validators.ts
- packages/mds-attachment-service/tsconfig.build.json
- packages/mds-audit-service/package.json
- packages/mds-audit-service/service/validators.ts
- packages/mds-audit-service/tsconfig.build.json
- packages/mds-geography-service/package.json
- packages/mds-geography-service/service/validators.ts
- packages/mds-geography-service/tsconfig.build.json
- packages/mds-ingest-service/package.json
- packages/mds-ingest-service/service/validators.ts
- packages/mds-ingest-service/tsconfig.build.json
- packages/mds-policy-service/package.json
- packages/mds-policy-service/service/validators.ts
- packages/mds-policy-service/tsconfig.build.json
- packages/mds-schema-validators/index.ts
Moving function to schema validators package to eliminate redundancy.
> Remove redundant schema validator functions.

- packages/mds-schema-validators/index.ts
Add support for base Joi validation options and value mutating effects such as `.default` and `stripUnknown`
> Update schema validator to support Joi validation options

- container-images/mds-agency/package.json
- container-images/mds-attachment-service/package.json
- container-images/mds-audit-service/package.json
- container-images/mds-audit/package.json
- container-images/mds-compliance/package.json
- container-images/mds-daily/package.json
- container-images/mds-geography-author/package.json
- container-images/mds-geography-service/package.json
- container-images/mds-geography/package.json
- container-images/mds-ingest-service/package.json
- container-images/mds-jurisdiction-service/package.json
- container-images/mds-jurisdiction/package.json
- container-images/mds-metrics-sheet/package.json
- container-images/mds-policy-author/package.json
- container-images/mds-policy-service/package.json
- container-images/mds-policy/package.json
- container-images/mds-web-sockets/package.json
- jest.config.js
- package.json
- packages/mds-audit/package.json
- packages/mds-webpack-config/index.ts
- packages/mds-webpack-config/package.json
- yarn.lock
Migrate to latest version of `webpack`
> Upgrade to Webpack v5

- packages/mds-geography-author/package.json
- packages/mds-geography/package.json
- packages/mds-policy-author/package.json
Some packages were marked private so they were not getting published.
> Make packages public so they publish properly

- packages/mds-jurisdiction/handlers/create-jurisdiction.ts
- packages/mds-jurisdiction/handlers/delete-jurisdiction.ts
- packages/mds-jurisdiction/handlers/get-jurisdiction.ts
- packages/mds-jurisdiction/handlers/get-jurisdictions.ts
- packages/mds-jurisdiction/handlers/update-jurisdiction.ts
- packages/mds-jurisdiction/index.ts
For API client support
mds-jurisdiction
> [mds-jurisdiction] Export needed jurisdiction types

- packages/mds-jurisdiction/index.ts
> [mds-jurisdiction] export few more jurisdiction api types

- packages/mds-metrics-sheet/package.json
- yarn.lock
Fixes audit advisory
- mds-metrics-sheet
> [mds-metrics-sheet] Bump google spreadsheets to resolve vulnerability

- packages/mds-attachment-service/jest.config.js
More Jenkins stuff...
- mds-attachment-service (tests)
> [mds-attachment-service] Reduce coverage for attachment service temporarily

- Jenkinsfile
- package.json
- packages/mds-metrics-sheet/metrics-log.ts
- packages/mds-repository/@types/index.ts
- packages/mds-repository/mixins/identity-column.ts
- packages/mds-repository/mixins/recorded-column.ts
- pnpm-lock.yaml
Upgrade to latest [TypeScript 4.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/) release.
> KTLO: Upgrade to TypeScript 4.2

- packages/mds-cache/redis/helpers/client.ts
- packages/mds-collector-backend/index.ts
- Export SchemaValidator for JSON Schema validation
- Make redis connection logs more informative
> Minor changes

- values.yaml.tpl
Adds missing template entries
Bad values-mds.yaml output
n/a
> Add mds-transaction-service and mds-transaction-api to values template

- Jenkinsfile
- packages/mds-collector-backend/service/provider.ts
- packages/mds-transaction-service/@types/index.ts
- packages/mds-transaction-service/repository/entities/transaction-entity.ts
- packages/mds-transaction-service/repository/index.ts
- packages/mds-transaction-service/repository/migrations/1615586339528-TransactionsSearchIndicies.ts
- packages/mds-transaction-service/repository/migrations/index.ts
- packages/mds-transaction-service/test-fixtures/index.ts
- packages/mds-transaction-service/tests/transactions.spec.ts
*[adds full-text search to receipt json, range filtering on amount, matching on fee_type]*
*[mds-transactions-service]*
> Search on fee_type, amount, and receipt json

- packages/mds-providers/index.ts
Adds Circ Provider Entry from https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv
Resovles #577
- mds-providers
> [mds-providers] Add Circ Provider Entry

- values.yaml.tpl
make `pnpm values` work for new old policy containers
> Fix values template

- Jenkinsfile
Resolve out-of-memory (OOM) errors when Jenkins runs the test suites.
https://jenkins.aws.lacuna.ai/job/mds-core-github-tester/job/PR-637/3/console
If this PR branch passes testing, we should be good to go.
> Fix nodejs out-of-memory errors in Jenkins

- packages/mds-ingest-service/@types/index.ts
- packages/mds-ingest-service/client/index.ts
- packages/mds-ingest-service/repository/index.ts
- packages/mds-ingest-service/service/manager.ts
- packages/mds-ingest-service/service/provider.ts
- packages/mds-ingest-service/service/validators.ts
- packages/mds-ingest-service/tests/index.spec.ts
Implements missing get devices ingest service call.
Missing get devices call.
* mds-ingest-service
> implemented get devices

- packages/mds-ingest-service/repository/index.ts
- packages/mds-ingest-service/repository/migrations/1603212540962-CreateEventsTable.ts
- packages/mds-ingest-service/repository/migrations/1625676583247-AddEventsTripIdTimestampIndex.ts
- packages/mds-ingest-service/tests/index.spec.ts
*[fixes bad query, and missing indicies for mds1.0 events]*
*[mds-ingest-service]*
> fixes all_events query to use start/end, adds missing indicies
