.vscode/launch.json
packages/mds-agency/package.json
packages/mds-api-authorizer/package.json
packages/mds-api-server/package.json
packages/mds-audit/package.json
packages/mds-compliance/package.json
packages/mds-daily/package.json
packages/mds-db/package.json
packages/mds-logger/package.json
packages/mds-metrics-sheet/package.json
packages/mds-native/package.json
packages/mds-policy-author/package.json
packages/mds-policy/package.json
packages/mds-provider/package.json
packages/mds-types/package.json
packages/mds-utils/package.json

Tests will _occasionally_ timeout when port forwarding to Postgres and Redis running inside Kubernetes. Increase the _mocha_ timeout above the default of 2s to mitigate this.

Increase test timeout to support k8s DB/Redis

---

bin/mdsctl
bin/mdsctl-completion.bash

support traditional command options, by short-and-long key, eg:
- `% mdsctl -p [preset[,preset]] ...`
- `% mdsctl --preset [preset[,preset]] ...`
- `% mdsctl --preset=[preset[,preset]] ...`
support tab completion, eg:
- `% . <(mdsctl completion)`
- `% mdsctl<tab><tab>`
- `% mdsctl -<tab><tab>'

support traditional command options and tab completion

---

package.json
packages/mds-api-server/index.ts
packages/mds-api-server/package.json
packages/mds-audit/api.ts
packages/mds-native/api.ts
packages/mds-provider/api.ts
packages/mds-provider/tests/test.ts
yarn.lock

Added a standard way to log requests across all APIs. By default only `400/500` errors are logged, but that is controllable via the `API_REQUEST_LOG_LEVEL` environment variable. When enabled, logs containing `:method :url :status :res[content-length] - :response-time ms` are emitted via `mds-logger`
```
INFO GET /provider/status_changes 200 5896 - 71.805 ms
INFO GET /provider/status_changesd 404 163 - 2.178 ms
INFO GET /provider/status_changes 200 5896 - 22.579 ms
INFO GET /agency 200 97 - 6.518 ms
INFO GET /agency/health 200 216 - 1.245 ms
INFO GET /agency/vehicles 200 9476 - 67.195 ms
INFO GET /native 200 97 - 4.252 ms
INFO GET /native/health 200 215 - 1.226 ms
INFO GET /native/vehicles/68fd5e1d-55c5-45b7-b000-13831fd77507 404 125 - 51.734 ms
INFO GET /native/providers 200 3767 - 1.610 …
```

Add standard API request logging

---

helm/mds/templates/ingress.yaml

When a wildcard domain (`"*"` or `"*.something.domain"` for example) is specified, the string needs to be quoted to be valid YAML - a bare asterisk character throws a helm error.

need to quote domains in case of a wildcard globa ("*")

---

bin/mdsctl

Fixes an unfortunate typo in the templateValues() function of mdsctl

[mdsctl] fix - values.yaml not .html

---

packages/mds-metrics/request-handlers.ts
packages/mds-metrics/tests/test.ts
packages/mds-metrics/types.ts
packages/mds-metrics/utils.ts
packages/mds-types/index.ts

This is what happens when you don't have tests yet ;)

[mds-metrics] Fix binning bug

---

packages/mds-db/geographies.ts
packages/mds-db/tests/mds-db.spec.ts

[mds-db] Fix `editGeography`

---

packages/mds-agency/utils.ts

@wesleyfsmith and I were pairing and calling the agency event API and getting a very confusing error message. Turns out we were indeed missing the timestamp field, but the message was saying `error_type`.

[mds-agency] Fix bad event missing timestamp error message

---

bin/mdsctl

patch mdsctl to (un)install istio-1.2.6 via helm directly
note:
- the feature/jwtodd-nats branch u/d istiio-1.3.5
- more extensive testing was done locally then that included below, namely `./bin/mdsctl build install:mds`
considerations:
- thought about preemptively deleting instio-init post install but opted to let it reside till it is better understood
verify:
```
% ./bin/mdsctl install:istio
% kubectl get pods -n istio-system
[istio pods]
% helm list
...
istio     	1       	Wed Nov 13 16:27:14 2019	DEPLOYED	istio-1.2.6     	1.2.6      	istio-system
istio-init	1       	Wed Nov 13 16:27:08 2019	DEPLOYED	istio-init-1.2.6	1.2.6      	istio-system
% ./bin/mdsctl uninstall:istio
% kubectl get namespaces
% helm list
```

mdscl/istio: install (un)install via helm straight up

---

helm/mds/templates/configmap.yaml

Fix an error in `mdsctl install:mds` when there are no mounted/symlink'ed config files. Also, now supports `json` _and/or_ `json5` file combinations.

Fix helm configmap glob

---

packages/mds-audit/service.ts
packages/mds-cache/index.ts
packages/mds-db/audits.ts

We've received field reports that the audit mobile app can be slow when looking a device up by VIN, viewing devices on the map, and submitting issues. These reports are documented in [MDSAAS-357](https://lacunadotai.atlassian.net/browse/MDSAAS-357), [MDSAAS-362](https://lacunadotai.atlassian.net/browse/MDSAAS-362), and [MDSAAS-363](https://lacunadotai.atlassian.net/browse/MDSAAS-363). Since each of these activities involve lots of different db, cache, and data processing operations, collecting timing stats on the relevant code blocks should tell us where to focus our performance improvement efforts.

[mds-cache, mds-db] Instrument some cache and db operations with timing logs

---

packages/mds-config-service/client.ts
packages/mds-config-service/index.ts
packages/mds-config-service/tests/client.spec.ts
packages/mds-config/api.ts
packages/mds-config/tests/api.spec.ts
packages/mds-config/types.ts

Allow merging multiple settings properties with one GET request.
A single settings property is specified as a route param: 
`GET /config/settings/{property}`
Multiple settings properties are specified as query string parameters: 
`GET /config/settings?p={property1}&p={property2}`

Support merging multiple settings properties

---

packages/mds-audit/api.ts
packages/mds-audit/service.ts
packages/mds-cache/index.ts

Audit's "get vehicles by bbox" endpoint fetches events from redis using a `georadiusAsync` call, which accepts a circle (lat, lng, and radius) as its argument. The circle we use for this argument inscribes the original bbox, so there is an extra check to remove events outside the requested bbox from the response.
The audit mobile app can live without this extra check, so this PR adds an option to skip it and potentially speed up the endpoint.
Refs [MDSAAS-362](https://lacunadotai.atlassian.net/browse/MDSAAS-362).

[mds-audit] Add option to skip bbox check when fetching vehicles

---

packages/mds-audit/service.ts
packages/mds-cache/index.ts

The VIN lookup endpoint currently calls `db.readDeviceByVehicleId`, then `cache.readDevice`, then `cache.readEvent`. This PR should make those two cache fetches execute in parallel. I expect that to be effective because (somewhat surprisingly) the cache seems to be the bottleneck in this endpoint:
| Function | Mean response time (s) | p95 response time (s) |
| ------------------------- | ----------- | --------- |
| Get VIN endpoint handler | 4.08 | 18.9 |
| db.readDeviceByVehicleId | 0.8 | 3.5 |
| cache.readDevice | 1.8 | 6.5 |
| cache.readEvent | 3.1 | 8.9 |
Refs [MDSAAS-357](https://lacunadotai.atlassian.net/browse/MDSAAS-357).
Please let me know if there's a cleaner / more idiomatic way to write this `Promise.all`.

[mds-audit] Speed up VIN lookup by parallelizing cache reads

---

bin/mdsctl
packages/mds-cache/index.ts

converts the branch name into the suffix in the docker image tag.  Prevents competing branches from stomping on each others' build output.

use branch name for docker image tag suffix

---

container-images/mds-web-sockets/index.ts

This enables the `about` (HTTP GET `$HOST/mds-websockets/`) to return a well-formed response. E.g.
```json
{
"name": "@container-images/mds-web-sockets",
"version": "0.0.1",
"build": {
"date": "2019-12-21T16:04:08.459Z",
"branch": "bugfix/neil/env-inject-web-sockets",
"commit": "ab47f5d"
},
"node": "10.16.3",
"status": "Running"
}
```

[mds-web-sockets] Add proper env-injection to mds-web-sockets

---

packages/mds-agency/request-handlers.ts
packages/mds-agency/utils.ts
packages/mds-web-sockets/client.ts

Previously, agency/telemetry POST requests would send a 400 response to clients on a failed write to cache/stream/socket; this PR resolves the extraneous error bubbling to the API client. It also adds a basic health check to the internal WebSocket client used by agency to validate that the WebSocket http server is running before attempting to establish a connection.

[mds-agency] [mds-web-sockets] Improve agency/telemetry error handling, and add basic health check to WebSocket client

---

packages/mds-utils/state-machine.ts
packages/mds-utils/tests/utils.spec.ts
packages/mds-utils/utils.ts

The `isTransitionValidOld()` will be removed, I left it in to verify compliance with the existing implementation.
At some point I'd like to re-evaluate the `VEHICLE_STATUS`/`VEHICLE_STATUSES`/`EVENT_STATUS_MAP`/`STATUS_EVENT_MAP` stuff so we could just lean on this dictionary as well. I'd also like to re-evaluate our custom rolled `Enum` implementation.

[mds-utils] Unify state transition representation

---

packages/mds-metrics/api.ts
packages/mds-metrics/package.json
packages/mds-metrics/request-handlers.ts
packages/mds-metrics/tests/request-handlers.test.ts
packages/mds-metrics/types.ts
packages/mds-types/scopes.ts

`/metrics/all` accepts the scopes `metrics:read` and `metrics:read:provider`
`metrics:read` allows reading from any provider. If the `provider_id` query param is not specified, the SQL query will return all providers. If one or more `provider_id` query params are supplied, we will only query for those specified providers.
`metrics:read:provider` only allows querying of the associated `provider_id` in the claim. If no provider id is specified, or if provider ids besides the JWT claimed provider id are given, we always only query the JWT `provider_id`.

[mds-metrics] Fixes metrics scope processing

---

packages/mds-metrics/request-handlers.ts

This forwards any time parsing `BadParamsError` thrown to the client

Forward date time parsing error to client

---

packages/mds-daily/db-helpers.ts

This resolves a performance issue in production causing last_day_stats_by_provider to not ever respond due to an ~75s query `db.getMostRecentEventByProvider()`. Actually providing fallback logic based on validation of the cache response will be added in a subsequent PR.

[mds-daily] *URGENT PATCH* Assume cache as source-of-truth for getTimeSinceLastEvent

---

helm/mds/templates/cronjob.yaml

istio-enabled cronjobs are not being disposed of upon exit given the istio-sidecar container remains alive.
istio-enabling cronjobs provides no value, that i am aware of, at this time ... could be wrong, over time.
test:
- tested by inspecting `helm template ./helm/mds -x templates/cronjob.yaml`

disable istio for cronjob deployments

---

packages/mds-config-service/client.ts
packages/mds-config-service/tests/client.spec.ts
packages/mds-config/api.ts
packages/mds-config/tests/api.spec.ts
packages/mds-config/types.ts
packages/mds-provider-processor/src/configuration.ts
packages/mds-trip-processor/src/configuration.ts
packages/mds-utils/date-time-utils.ts

You can now include `?partial=true` to receive `null` values for settings and a `200 OK` rather than a `404 Not Found` error. 
```json
{
"providers": [
{
"provider_name": "...",
"provider_id": "..."
}
],
"foo": null
}
```
Also, cleaned up the response body for `404 Not Found` errors to provide insight into what properties failed without leaking any server setup information.
```json
{
"name": "NotFoundError",
"reason": "Settings Not Found",
"info": {
"found": [
"providers"
],
"missing": [
"foo"
]
}
}
```
Also, added corresponding tests to maintain coverage:
`@mds-core/mds-config-service`
```
-----------|---------|----------|---------|---------|-------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```

Update Config API to support partial configs

---

packages/mds-orm/connections.ts

Only run migrations on the designated R/W connection.

Use R/W connection for running TypeORM migrations

---

helm/mds/templates/auth.yaml

Auth is done internally by mds-web-socketrs due to different headers for ws protocol

carve out exception to jwt auth for websockets api 

---

okteto.yml
packages/mds-agency/package.json
packages/mds-agency/request-handlers.ts
packages/mds-event-server/index.ts
packages/mds-web-sockets/package.json
packages/mds-web-sockets/server.ts

This allows us to avoid having to create a direct connection between agency and the web-sockets server. Massively improves scalability options, and some operational headaches we've been experiencing recently.

[mds-agency] [mds-web-sockets] Add NATS-Streaming consumption for mds-web-sockets

---

packages/mds-compliance/tests/api.spec.ts

This test was destined to fail starting yesterday...

Fix failing compliance test

---

packages/mds-stream-processor/labelers/geography-labeler.ts
packages/mds-stream-processor/package.json
packages/mds-stream-processor/tests/labelers/geograpy-labelers.spec.ts
packages/mds-stream-processor/tests/labelers/latency-labeler.spec.ts

There are future improvements in the pipeline for this logic (calculating surrounding bbox to speed up worst-case PIP checks, only read from db on init and then read incoming geos from stream, etc)...

[mds-stream-processor] Add geo labeling for mds-stream-processor

---

tsconfig.settings.json

Node.js has 100% support for ES2019 in v12.14.1
Enabling the new 2019 features by updating the TypeScript target. Here are some of the more useful bits now available:

Enable ES2019 features in node:12.14.1-alpine

---

packages/mds-jurisdiction-service/@types/index.ts
packages/mds-jurisdiction-service/server/handlers/create-jurisdiction-handler.ts
packages/mds-jurisdiction-service/server/handlers/create-jurisdictions-handler.ts
packages/mds-jurisdiction-service/server/handlers/delete-jurisdiction-handler.ts
packages/mds-jurisdiction-service/server/handlers/get-jurisdiction-handler.ts
packages/mds-jurisdiction-service/server/handlers/get-jurisdictions-handler.ts
packages/mds-jurisdiction-service/server/handlers/schemas.ts
packages/mds-jurisdiction-service/server/handlers/update-jurisdiction-handler.ts
packages/mds-jurisdiction-service/server/handlers/utils.ts
packages/mds-jurisdiction/handlers/create-jurisdiction.ts
packages/mds-jurisdiction/handlers/delete-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdictions.ts
packages/mds-jurisdiction/handlers/update-jurisdiction.ts
packages/mds-jurisdiction/handlers/utils.ts
packages/mds-jurisdiction/tests/api.spec.ts
packages/mds-schema-validators/validators.ts
packages/mds-types/index.ts

With the new service pattern I have been working on, I am trying to constrain functionality to the service layer resulting in less polluting of the global scope. In this PR, I basically move the type declarations for Jurisdictions from `mds-core` to `mds-jurisdiction-service/@types` ... also, I moved the schema definition/validation as well which required some minor changes to `mds-schema-validators` (basically exporting the _ValidateSchema_ function and a reference to `Joi` called _SchemaBuilder_
Eventually, I would like `mds-types` to include only things like _UUID_, _Timestamp_, etc and move the models to their respective service packages.

Move jurisdiction types/utils to service package

---

packages/mds-agency/agency-candidate-request-handlers.ts
packages/mds-agency/request-handlers.ts
packages/mds-agency/sandbox-admin-request-handlers.ts
packages/mds-api-helpers/index.ts
packages/mds-audit/api.ts
packages/mds-compliance/api.ts
packages/mds-geography/api.ts
packages/mds-jurisdiction-service/service/repository/index.ts
packages/mds-jurisdiction-service/tests/index.spec.ts
packages/mds-jurisdiction/api.ts
packages/mds-jurisdiction/handlers/create-jurisdiction.ts
packages/mds-jurisdiction/handlers/delete-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdictions.ts
packages/mds-jurisdiction/handlers/update-jurisdiction.ts
packages/mds-jurisdiction/handlers/utils.ts
packages/mds-jurisdiction/package.json
packages/mds-jurisdiction/tsconfig.build.json
packages/mds-metrics-service/service/repository/index.ts
packages/mds-metrics-service/service/repository/migrations/1585847425124-CreateMetricsTable.ts
packages/mds-metrics-service/tests/index.spec.ts
packages/mds-repository/repository.ts
packages/mds-service-helpers/index.ts
packages/mds-service-helpers/tests/index.spec.ts
packages/mds-utils/utils.ts

Converted `ServiceResponse` from a typed tuple to a discriminated type union. This provides enhanced type-checking when processing service responses by forcing consumers (e.g. an API) to handle the error before accessing the result.
Alternatively,  consumers can use a service response handler that invokes typed error/result methods.

Improved service error/result types and handling

---

container-images/mds-event-processor/index.ts
container-images/mds-telemetry-processor/index.ts
packages/mds-stream-processor/labelers/device-labeler.ts
packages/mds-stream-processor/processors/vehicle-event-processor.ts
packages/mds-stream-processor/processors/vehicle-telemetry-processor.ts
packages/mds-stream-processor/server.ts

I noticed this in the k8s logs for both `mds-event-processor` and `mds-telemetry-processor` pods. Each container should only be referencing one processor. This was due to the stream processors being initialized on export. Changed processors to export a factory function that can be used to initialize them instead.
```                                                                        │
│ INFO "Creating KafkaStreamSink" "mds.event.annotated" {"clientId":"mds-event-processor"}                             │
│ INFO "Creating KafkaStreamSource" "mds.event" {"groupId":"mds-event-processor"}                                      │                                                                         │
│ INFO "Creating KafkaStreamSink" "mds.telemetry.annotated" …
```

Export processors as functions instead of values

---

packages/mds-agency/request-handlers.ts
packages/mds-agency/sandbox-admin-request-handlers.ts
packages/mds-api-helpers/index.ts
packages/mds-audit/api.ts
packages/mds-compliance/api.ts
packages/mds-geography/api.ts
packages/mds-jurisdiction/handlers/get-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdictions.ts
packages/mds-utils/utils.ts

This will allow for additional options/functionality without changing the signature since this will eventually be used in many places.

Make the parser part of an options object

---

packages/mds-cache/package.json
packages/mds-cache/tsconfig.build.json
packages/mds-cache/unflatteners.ts
packages/mds-schema-validators/validators.ts

`mds-schema-validators` had an undeclared (and perhaps ill-advised) dependency on `mds-cache`

Remove undeclared mds-cache dependency

---

bin/mdsctl
container-images/mds-metrics-processor/Dockerfile
container-images/mds-metrics-processor/package.json
container-images/mds-metrics-processor/tsconfig.build.json
container-images/mds-metrics-processor/webpack.config.ts
helm/mds/tests/service-all-disabled_test.yaml
helm/mds/values.yaml
helm/mds/values.yaml.tpl
packages/mds-stream-processor/controller.ts
packages/mds-stream-processor/metrics.ts
packages/mds-stream-processor/package.json
packages/mds-stream-processor/processors/index.ts
packages/mds-stream-processor/processors/metrics-processor.ts
packages/mds-stream-processor/telemetry.ts
packages/mds-utils/utils.ts
tsconfig.json

Consume messages from mds.metrics
Write to database using metrics service

Initial mds.metrics stream processor

---

.nycrc.json
packages/mds-metrics-service/service/repository/mappers.ts
packages/mds-repository/connection-manager.ts
packages/mds-repository/migration.ts
packages/mds-repository/package.json
packages/mds-repository/repository.ts
packages/mds-repository/tests/connection-manager.spec.ts
packages/mds-service-helpers/index.ts
packages/mds-utils/index.ts
yarn.lock

Resolving a couple of issues with the repository.
- Pending migrations are checked, run, and logged when a repository is initialized; not on each connect.
```
INFO "Created ro connection: metrics-ro-4991d246-d7cf-46f5-80af-52a6a393bb70"
INFO "Created rw connection: metrics-rw-4991d246-d7cf-46f5-80af-52a6a393bb70"
INFO "Ran 2 migrations (metrics-migrations): CreateRepository0000000000001, CreateMetricsTable1588016731204"
```
- Added a mutex lock on connection creation to avoid the chaos that results when multiple queries are initiated concurrently at startup.
Also:
- Re-enabled code-coverage checks

[mds-repository] connection manager improvements

---

packages/mds-jurisdiction-service/service/repository/mappers.ts
packages/mds-metrics-service/@types/index.ts
packages/mds-metrics-service/service/repository/entities/metric-entity.ts
packages/mds-metrics-service/service/repository/mappers.ts
packages/mds-metrics-service/service/repository/migrations/1588016731204-CreateMetricsTable.ts
packages/mds-metrics-service/tests/index.spec.ts
packages/mds-repository/naming-strategies/mds-naming-strategy.ts
packages/mds-repository/tests/naming-strategies.spec.ts
packages/mds-repository/utils.ts

Add support for storing and querying null dimensions/aggregates. Not all dimensions will be applicable to all metrics and not all aggregates will be calculated for all metrics. This requires creating a new unique index as Postgres does not support null values columns used in primary keys.

Metrics Model Changes

---

.eslintrc.json
packages/mds-jurisdiction-service/@types/index.ts
packages/mds-jurisdiction-service/service/handlers/delete-jurisdiction-handler.ts
packages/mds-jurisdiction-service/service/handlers/get-jurisdiction-handler.ts
packages/mds-jurisdiction-service/service/handlers/update-jurisdiction-handler.ts
packages/mds-jurisdiction-service/service/repository/entities/jurisdiction-entity.ts
packages/mds-jurisdiction-service/service/repository/index.ts
packages/mds-jurisdiction/handlers/delete-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdiction.ts
packages/mds-jurisdiction/handlers/update-jurisdiction.ts
packages/mds-metrics-service/service/repository/entities/metric-entity.ts
packages/mds-metrics-service/service/repository/index.ts
packages/mds-repository/connection.ts
packages/mds-repository/repository.ts
packages/mds-repository/tests/connection.spec.ts

This greatly simplifies repository definition. No longer necessary to call `CreateRepositoryMethod/CreateRepository` or to pass around a `connect` function.

Implement an abstract repository class

---

packages/mds-api-authorizer/index.ts
packages/mds-api-authorizer/package.json
packages/mds-api-authorizer/tests/index.spec.ts

I think the issue only exists when running tests, but the solution feels more correct anyway. Added tests that override the environment variables.

Fix a potential issue with handling process.env

---

packages/mds-service-helpers/client/index.ts
packages/mds-service-helpers/tests/index.spec.ts

Based on feedback, there is now an alternative to `handleServiceResponse` for getting the result of a service call and starting a separate exception chain in the consumer in the event of a service error.
Using `handleServiceResponse`:
```ts
export const GetJurisdictionsHandler = async (req: GetJurisdictionsRequest, res: GetJurisdictionsResponse) => {
handleServiceResponse(
await JurisdictionServiceClient.getJurisdictions(),
error => {
return res.status(500).send({ error })
},
jurisdictions => {
return res.status(200).send({ 
version: res.locals.version, 
jurisdictions: jurisdictions.filter(HasJurisdictionClaim(res)) 
})
}
)
}
```
Using `getServiceResult`:
```ts
export const GetJurisdictionsHandler = async (req: GetJurisdictionsRequest, res: GetJurisdictionsResponse) => {
try {
const …
```

Make async getServiceResult helper

---

packages/mds-daily/request-handlers.ts
packages/mds-jurisdiction-service/service/repository/index.ts
packages/mds-stream/kafka/stream-consumer.ts
packages/mds-stream/kafka/stream-producer.ts
packages/mds-utils/tests/utils.spec.ts
packages/mds-utils/utils.ts

[mds-utils] Move generic passing in isDefined so T can be properly inferred

---

package.json
yarn.lock

Unfortunately, we need to roll back to TypeScript 3.8. The new TypeScript (and the corresponding new tslib) change the way that module exports are emitted. While the new modules work just fine when published and installed in another repo, the tslib changes break the ability for `Sinon` to mock the exported functions. Reverting until Sinon catches up or provides guidance.

Roll back typescript/tslib

---

packages/mds-audit/api.ts

Just removing a redundant line.

[mds-audit] Extremely small audit fix.

---

packages/mds-service-helpers/@types/index.ts
packages/mds-service-helpers/client/index.ts
packages/mds-service-helpers/server/index.ts
packages/mds-service-helpers/tests/index.spec.ts

Minor change to allow custom error types so that system isn't locked into the predefined set.
This is a totally backwards compatible change. The following code segments are equivalent:
```ts
if (isServiceError(error)) {
if (error.type === 'NotFoundError') {
return res.status(404).send({ error })
}
}
```
```ts
if (isServiceError(error, 'NotFoundError')) {
return res.status(404).send({ error })
}
}
```
Services can now return a custom error:
```ts
return ServiceError({ type: 'CustomError', message: 'Custom error message' })
```
Which can be handled using the new signature:
```ts
if (isServiceError(error, 'CustomError')) {
return res.status(400).send({ error })
}
}
```

Add custom service error type support

---

.vscode/launch.json
packages/mds-geography-author/tests/api.spec.ts
packages/mds-policy-author/tests/api.spec.ts
packages/mds-schema-validators/validators.ts

The POST and PUT endpoints for the Policy and Geography authoring APIs should reject any payloads where the client specifies a publish_date. This is something that should _only_ be set by the `.../publish` APIs. 
Also, added in launch configs for the geography-authoring API

[mds-policy-author] [mds-geography-author] Reject payloads that specify a publish_date

---

packages/mds-geography-author/api.ts
packages/mds-geography-author/tests/api.spec.ts
packages/mds-geography-author/types.ts
packages/mds-geography/api.ts
packages/mds-geography/tests/api.spec.ts
packages/mds-geography/types.ts
packages/mds-policy-author/api.ts
packages/mds-policy-author/tests/api.spec.ts
packages/mds-policy-author/types.ts

After discussing with @avatarneil , since the current OMF spec (0.4.1) has a `data` payload in `Policy`, we'll add it to these endpoints to keep it consistent.

[mds-policy-author][mds-geography*] Fix/add data payload to policy author and geo services

---

packages/mds-stream/kafka/stream-producer.ts

There's a bug in the logic that results in a write _always_ falling through to throwing a ClientDisconnectedError. FWIW, we probably ought to not be returning a Promise<void> for writes, but we can revisit that another time. 
mds-stream
mds-agency

[mds-stream] [mds-agency] Add missing return statement for kafka writes

---

packages/mds-policy/api.ts
packages/mds-policy/tests/api.spec.ts
packages/mds-policy/types.ts

[mds-policy] Adding data envelop back to mds-policy and correcting version number

---

packages/mds-stream/nats/helpers.ts

Though typescript/webpack do not complain, it appears that if you use a default-style import for ts-nats at runtime the methods are unable to be resolved. Tests are lacking for everything in mds-stream, and we ought to improve that at some point soon. This has been tested in one of our development environments and resolves the issue. I will probably cut a PR to update the typing for the ts-nats library at some point, too.
mds-stream
mds-agency
mds-web-sockets

🐛[mds-stream] Change ts-nats import to properly resolve methods

---

packages/mds-jurisdiction-service/client/index.ts
packages/mds-jurisdiction-service/server/index.ts
packages/mds-jurisdiction-service/service/provider.ts
packages/mds-jurisdiction-service/tests/index.spec.ts
packages/mds-jurisdiction/tests/api.spec.ts
packages/mds-service-helpers/@types/index.ts
packages/mds-service-helpers/server/index.ts
packages/mds-service-helpers/tests/index.spec.ts

Separate the `ProcessController` and `ServiceProvider` methods into separate interfaces. 
This change allows more flexibility when creating networked services.

[mds-service-helpers] Create separate ProcessController interface

---

packages/mds-jurisdiction-service/package.json
packages/mds-repository/package.json
yarn.lock

Upgrade to latest TypeORM version. Also, listing TypeORM as a peer dependency of mds-repository which is installed as a dependency in other projects/packages.
TypeORM `instanceof` check failures in modules that depend on `mds-repository` and use a different version of TypeORM as described generally this [article](https://classic.yarnpkg.com/blog/2018/04/18/dependencies-done-right/).

Upgrade TypeORM

---

packages/mds-agency/request-handlers.ts

Previously, the agency logs for validation errors weren't great: 
```
"Device ValidationError for JUMP. Error: ValidationError: invalid_value".
```
Now, they're significantly improved: 
```
INFO "Device ValidationError for c3e036fd-71cc-474e-aa46-c3750bc20115. Error: {\"name\":\"ValidationError\",\"reason\":\"invalid_value\",\"info\":{\"value\":{\"provider_id\":\"c3e036fd-71cc-474e-aa46-c3750bc20115\",\"device_id\":\"\",\"vehicle_id\":\"ec5547b3-76e2-4882-8816-16a746f5362f\",\"type\":\"car\",\"propulsion\":[\"combustion\"],\"year\":1990,\"mfgr\":\"foo inc\",\"model\":\"i date one\",\"recorded\":1591029035661,\"status\":\"removed\"},\"details\":\"value.device_id is required\"}}"
```
mds-agency

[mds-agency] Add better agency validation error logs

---

bin/mdsctl

`yarn image` currently fails if your current k8s cluster can't be reached. I think this ought to be a warning rather than a hard failure.
No JIRA tracking atm
*mdsctl*

Patch warning msg

---

package.json

Detect dependencies for known security vulnerabilities in a way that will cause CI failures by running `yarn audit` as part of `yarn clean`

Run yarn audit to detect security vulnerabilities

---

packages/mds-api-server/index.ts
packages/mds-api-server/tests/index.spec.ts

`mds-api-server` binds a default route at the root of the `PATH_PREFIX` that has limited value and prevents APIs from attaching more specific functionality at that path and can lead to some awkward route naming, such as `GET /metrics/metrics`. The information available in the former response at `/` is still available under `/health`

Remove default home route handler

---

packages/mds-web-sockets/tests/ws.spec.ts
packages/mds-web-sockets/ws-server.ts

This fixes a bug where the entity name passed in was not being used in the Nats subject.  It was still using hardcoded 'event' name.  Let me know if there's a straighforward way this can be tested to avoid.  I added an additional telemetry test which doesn't actually test this code path for the fix.
mds-web-sockets

Ensure entity name is used in Nats subject name, add telemetry test

---

helm/mds/templates/deployment.yaml
helm/mds/values.yaml

NATS and Kafka default to disabled.  When enabled, helm will use the hostname provided in values.yaml.

Fix NATS and Kafka default values

---

helm/mds/templates/egress.yaml

This was causing an error when `egress:` was defined with no hosts.  Not required for mds-core functionality.

remove extraneous egress serviceentry

---

packages/mds-service-helpers/@types/index.ts

Type alias that can be used to reduce the number of nested generics for readability.

Add a new service provider helper type

---

packages/mds-stream/kafka/helpers.ts
packages/mds-stream/kafka/stream-consumer.ts
packages/mds-stream/kafka/stream-producer.ts

Currently, if you start a package that uses mds-stream's kafka features (e.g. mds-agency) in an environment that does not have Apache Kafka, there is a copious amount of log-spam. This PR removes the default value for KAFKA_HOST from the code, and instead makes it so you cannot initialize a consumer/producer (will just return null).
[mds-stream]

[mds-stream] Remove KAFKA_HOST default from the code to reduce log spam

---

packages/mds-logger/index.ts

Trying to scrape through logs without timestamps is a pain. This adds both a human-readable ISO timestamp as well as a ms-since-epoch timestamp to all of our logs.
[mds-logger]

Add MS since epoch and ISO timestamps to mds-logger

---

packages/mds-geography-author/api.ts
packages/mds-geography-author/tests/api.spec.ts
packages/mds-geography/api.ts
packages/mds-geography/tests/api.spec.ts
packages/mds-policy-author/api.ts
packages/mds-policy-author/tests/api.spec.ts
packages/mds-policy/api.ts
packages/mds-policy/tests/api.spec.ts

The recent changes we made to the error handling in the above packages was broken due to an incorrect signature for the global error handling method. This resulted in a spectacularly confusing stack trace when a client attempted to hit a route which was not defined by the API, eventually resulting in the server never responding to the client at all.
[mds-policy]
[mds-policy-author]
[mds-geography]
[mds-geography-author]

[mds-policy] [mds-policy-author] [mds-geography] [mds-geography-author] Fix signature for error handling middleware

---

.pre-commit-config.yaml
packages/mds-jurisdiction-service/service/handlers/create-jurisdiction-handler.ts
packages/mds-jurisdiction-service/service/handlers/create-jurisdictions-handler.ts
packages/mds-jurisdiction-service/service/handlers/delete-jurisdiction-handler.ts
packages/mds-jurisdiction-service/service/handlers/get-jurisdiction-handler.ts
packages/mds-jurisdiction-service/service/handlers/get-jurisdictions-handler.ts
packages/mds-jurisdiction-service/service/handlers/update-jurisdiction-handler.ts

- RepositoryError is a factory method used to wrap database errors
- It should not be called from the service handler methods

Remove redundant RepositoryError calls

---

packages/mds-repository/naming-strategies/mds-naming-strategy.ts
packages/mds-repository/tests/naming-strategies.spec.ts

Control the naming of Foreign Keys generated by migrations.

Add foreign key to naming strategy

---

packages/mds-compliance/mds-compliance-cli.ts
packages/mds-compliance/mds-compliance-engine.ts
packages/mds-compliance/tests/engine-test.spec.ts
packages/mds-compliance/types.ts
packages/mds-types/index.ts

The output from Compliance today truncates some data as an artifact from when it used to live in AWS Lambda. This extends the information about vehicles which are in violation of a Rule to have much more comprehensive output (full device info + latest event/telemetry)
- [mds-compliance]

[mds-compliance] Extend Compliance Output

---

packages/mds-web-sockets/package.json
packages/mds-web-sockets/ws-server.ts

When we consume data from the NATS interface, it already comes through in stringified-form. Currently, the processor we define in web-sockets to consume that data does an additional stringification. This PR removes the additional stringification.
Additionally, also fixes some launch-config issues.
mds-web-sockets

[mds-web-sockets] Don't doubly-stringify things

---

.iyarc
package.json
yarn.lock

Allow some vulnerability advisories to be excluded until a fix is available so that builds will not perpetually fail `yarn audit`
```
Improved Yarn Audit - v2.2.1
Reading excluded advisories from .iyarc
Minimum severity level to report: low
Excluded Advisories: [1523]
Running yarn audit...
Found 0 vulnerabilities
206 ignored because of advisory exclusions
Run `yarn audit` for more information
```

Allow yarn audit advisory exclusions

---

packages/mds-db/client.ts
packages/mds-repository/connection.ts

MDS currently supports `PG_HOST`/`PG_HOST_READER` environment variables to be able to direct database read requests to dedicated read-only replicas. This PR extends this to include the notion of a read-only database user by introducing `PG_USER_READER` and `PG_PASS_READER` which can be used as an additional security measure to prevent database updates even if those credentials are used to connect to `PG_HOST`.

Add support for read-only database user

---

packages/mds-agency/api.ts
packages/mds-agency/server.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-api-server/index.ts
packages/mds-api-server/tests/index.spec.ts
packages/mds-audit/api.ts
packages/mds-audit/server.ts
packages/mds-audit/tests/api.spec.ts
packages/mds-compliance/api.ts
packages/mds-compliance/server.ts
packages/mds-compliance/tests/api.spec.ts
packages/mds-daily/api.ts
packages/mds-daily/server.ts
packages/mds-daily/tests/daily.spec.ts
packages/mds-geography-author/api.ts
packages/mds-geography-author/server.ts
packages/mds-geography-author/tests/api.spec.ts
packages/mds-geography/api.ts
packages/mds-geography/server.ts
packages/mds-geography/tests/api.spec.ts
packages/mds-jurisdiction/api.ts
packages/mds-jurisdiction/server.ts
packages/mds-jurisdiction/tests/api.spec.ts
packages/mds-policy-author/api.ts
packages/mds-policy-author/server.ts
packages/mds-policy-author/tests/api.spec.ts
packages/mds-policy/api.ts
packages/mds-policy/server.ts
packages/mds-policy/tests/api.spec.ts
packages/mds-utils/utils.ts

Deprecate the `pathsFor` function that binds an API route to an array of paths. The `pathPrefix` function should be used instead, not only in the API route handlers, but also when making API calls from unit tests. All of our tooling is PATH_PREFIX aware already. This will also allow certain Express middleware that don't support path arrays to also work with our PATH_PREFIX setting (e.g. Prometheus metrics).
A deprecation warning was added to the old `pathsFor` function to discourage future use.

Deprecate pathsFor in favor of pathPrefix

---

packages/mds-schema-validators/validators.ts

Trying to save a Geography containing a description or an effective_date would fail because those properties weren't included in the schema definition used by the validator.

Joi schema for Geography doesn't match interface

---

packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-compliance/tests/api.spec.ts
packages/mds-utils/utils.ts

Remove deprecated `pathsFor` utility. All code has been converted to use `pathPrefix` instead.

Remove deprecated pathsFor utility function

---

packages/mds-agency/agency-candidate-request-handlers.ts
packages/mds-agency/request-handlers.ts
packages/mds-agency/sandbox-admin-request-handlers.ts
packages/mds-api-helpers/index.ts
packages/mds-audit/api.ts
packages/mds-compliance/api.ts
packages/mds-jurisdiction/handlers/get-jurisdiction.ts
packages/mds-jurisdiction/handlers/get-jurisdictions.ts
packages/mds-policy/api.ts
packages/mds-utils/utils.ts

Express can sometimes pass query params in as `string`, but can also pass them in as `string[]` in the case that the user defines the given param multiple times (e.g. `?x=foo&x=bar`). This extends parseObjectProperties to handle these cases gracefully.
[mds-utils]
Anything that uses parseRequest

[mds-utils] Extend parseObjectProperties to accept string arrays

---

.iyarc

Our audit check is currently catching a dot-prop advisory. Dot-prop is a dependency of Lerna, and while there is an issue to resolve in the Lerna repo, it has not been addressed yet.

Re-add .iyarc and exclude dot-prop advisory failing due to lerna dependency

---

packages/mds-api-server/api-server.ts
packages/mds-api-server/middleware/http-context.ts
packages/mds-api-server/package.json
packages/mds-logger/index.ts
packages/mds-logger/package.json
yarn.lock

There is currently no information added to log messages which allows tracing of a particular request. This PR makes it such that logs in mds-logger will have the X-Request-Id header propegated to all log messages in the context of a given HTTP request, so we can trace logs through our different microservices. This header is set currently by istio, but could also be set by something like nginx. 
[mds-api-server]
[mds-logger]
[everything]

Add logging for X-Request-Id header to enable deep microservice tracing

---

packages/mds-repository/@types/index.ts
packages/mds-types/index.ts

These aliases can be used to define all nullable properties as being optional when performing inserts.

Define new type aliases

---

packages/mds-jurisdiction-service/client/index.ts
packages/mds-jurisdiction-service/server/manager.ts
packages/mds-rpc-common/@types/index.ts
packages/mds-rpc-common/client/index.ts
packages/mds-rpc-common/index.ts
packages/mds-rpc-common/server/index.ts

With the prior module structure, some values were only available by including `/dist` in the import path after publishing. This PR moves those declarations to the top-level module export.

Export common RPC declarations from top-level

---

packages/mds-api-server/api-server.ts
packages/mds-rpc-common/server/index.ts

Changing the order of the middleware binding to eliminate the `GET /prometheus` logs that appear every 60 seconds.

Reorder middleware to remove prometheus request logging

---

packages/mds-jurisdiction-service/tests/index.spec.ts
packages/mds-repository/connection.ts

Adding tests for running and reverting migrations for jurisdictions.

Add tests for jurisdictions migrations

---

container-images/mds-jurisdiction-service/Dockerfile
helm/mds/templates/deployment.yaml
helm/mds/templates/service.yaml
packages/mds-jurisdiction-service/package.json
packages/mds-jurisdiction-service/server/manager.ts
packages/mds-rpc-common/@types/index.ts
packages/mds-rpc-common/server/index.ts
packages/mds-rpc-common/tests/index.spec.ts

Support remote REPL for RPC Servers. This is a draft. Needs some additional work, but this is the general idea. This allows you to connect to a service pod via `telnet` and issue commands from the REPL using the client instance attached to the context.
```
telnet localhost 8011
Trying ::1...
Connected to localhost.
Escape character is '^]'.
@mds-core/mds-jurisdiction-service REPL> await getJurisdictions()
[]
@mds-core/mds-jurisdiction-service REPL>
```

RPC Server REPL

---

packages/mds-api-server/@types/index.ts

Add ApiError type for standard error format and use in ApiResponse, add new ExtractApiResponseBody type which can be used for taking an extension of ApiResponse, and returns the B (body) generic or ApiError. This can be useful when attempting to leverage the existing express types we have in the BE from a FE application.
mds-api-server

[mds-api-server] Refactor & add helper type on top of ApiResponse

---

.iyarc

Auditing for vulnerabilities is failing (and resulting in all builds failing) due to a recent NPM advisory https://www.npmjs.com/advisories/1556. Unfortunately, though `node-fetch` has been patched, a dependency of `rpc_ts`, `isomorphic-fetch`, requires version `^1.0.1`, which has not received this security patch. Considering `isomorphic-fetch` is a pretty dead package, it is unlikely this fix will ever land.

Ignore npm advisory 1556 due to isomorphic-fetch being a dead package

---

packages/mds-types/index.ts

Allow optional declaration of more specific types for metadata.

Support optional metadata specificity

---

packages/mds-stream/test-utils.ts

Make stream mocks apply until jest.restoreAllMocks or a similar function is called, instead of only mocking one invocation.
- [mds-stream]

[mds-stream] Mock implementation until cleared, not for only one call

---

packages/mds-schema-validators/package.json
packages/mds-schema-validators/validators.ts
yarn.lock

Switch to non-deprecated version of Joi. Bonus, this version includes TypeScript definitions.
`@hapi/joi` has been [deprecated](https://github.com/sideway/joi/issues/2411)

Update to the latest version of Joi schema validation library

---

packages/mds-schema-validators/validators.ts
packages/mds-types/index.ts

We previously had a tighter definition of what event_types could go under a particular state, however for MDS 1.0.0 that mapping is too prescriptive, and leads to possible gaps in Policy. This conforms more with the spec, but having a looser definition.
- mds-types
- mds-policy
- mds-policy-author
- mds-compliance

Make Policy typedef less prescriptive

---

packages/mds-types/package.json
packages/mds-types/tests/transformers/device_transformers_spec.ts
packages/mds-types/tests/transformers/vehicle_event_transformers_spec.ts
packages/mds-types/transformers/0_4_1_to_1_0_0/vehicle_events.ts
packages/mds-types/transformers/1_0_0_to_0_4_1/vehicle_events.ts

Remove circular dependenc between mds-utils and mds-types that was causing a compilation failure.
@avatarneil Sorry, I know you don't like it here, but it doesn't feel like it makes sense to have the 0.4.1 types in anywhere but mds-types, and then it feels weird separating them from the transformers code. I didn't want to stick them in `mds-agency`, cause the validators require the transformers, and stickng them in `mds-utils` would've caused another circular dependency since that depends on `mds-types`.
*[list of packages]*

Removing circular dependency on mds-utils

---

packages/mds-api-server/@types/index.ts

The previous version resulted in `res.locals.claims` being of type `any` ... this fixes that.

Fix ApiResponseLocalsClaims type declaration

---

.vscode/launch.json
packages/mds-schema-validators/index.ts
packages/mds-schema-validators/tests/v0_4_1/vehicle_event_validators.spec.ts
packages/mds-schema-validators/tests/validators.spec.ts
packages/mds-schema-validators/v0_4_1/index.ts
packages/mds-schema-validators/validators.ts
packages/mds-types/index.ts
packages/mds-types/tests/transformers/device_transformers_spec.ts
packages/mds-types/tests/transformers/vehicle_event_transformers_spec.ts
packages/mds-types/transformers/0_4_1_to_1_0_0/devices.ts
packages/mds-types/transformers/0_4_1_to_1_0_0/index.ts
packages/mds-types/transformers/0_4_1_to_1_0_0/vehicle_events.ts
packages/mds-types/transformers/1_0_0_to_0_4_1/devices.ts
packages/mds-types/transformers/1_0_0_to_0_4_1/index.ts
packages/mds-types/transformers/1_0_0_to_0_4_1/vehicle_events.ts
packages/mds-types/transformers/1_0_0_to_1_1_0/devices.ts
packages/mds-types/transformers/1_0_0_to_1_1_0/index.ts
packages/mds-types/transformers/1_0_0_to_1_1_0/vehicle_events.ts
packages/mds-types/transformers/@types/0_4_1.ts
packages/mds-types/transformers/@types/1_0_0.ts
packages/mds-types/transformers/@types/index.ts
packages/mds-types/transformers/index.ts
packages/mds-utils/state-machine.ts

Makes it so we can build on the 1.0.0 transformers changes by making taxi a followup version. Need to add transformers for 1.0.0 -> 1.1.0 (and the reverse).
mds-types
all-the-things

[mds-types] [all-the-things] Merge in changes from dev/upgrade-to-1.0, move 1.0 types to transformers folder, make Taxi-on-MDS be v1.1.0

---

packages/mds-api-server/middleware/raw-body-parser.ts
packages/mds-rpc-common/server/index.ts

Support to adjust the maximum size of an RPC request body on a per service basis.

Allow overriding max RPC request size

---

packages/mds-audit/service.ts

There are scenarios where the device information (specifically the vehicle_id) in the cache gets out of sync with the information in the database. This seems to happen on occasion when a provider updates a device's vehicle_id. There is a separate effort to diagnose that issue, but in the meantime, this fix will always use device information from the database which we know to be accurate.

AUDIT-64 Use device information from database

---

packages/mds-schema-validators/package.json
packages/mds-schema-validators/tests/validators.spec.ts
packages/mds-schema-validators/tsconfig.build.json
packages/mds-schema-validators/validators.ts

While overhauling the compliance code, which uses the event validators, I noticed a couple problems:
1. `validateEvents` actually just validates whether the parameter is an array, as opposed to `VehicleEvent[]`.
2. The `eventSchema` was never updated. This is definitely my mistake. I think I had assumed there was a test exercising the `eventSchema`, but it turns out, there wasn't one. I also added tests.
* mds-schema-validators

Fix events validator

---

packages/mds-stream/kafka/stream-consumer.ts
packages/mds-stream/nats/helpers.ts
packages/mds-stream/nats/stream-consumer.ts

This allows a single process/consumer to subscribe to multiple topics rather than requiring a separate process per topic.

Allow a stream consumer to subscribe to multiple topics

---

packages/mds-attachment-service/tests/index.spec.ts
packages/mds-audit-service/tests/index.spec.ts
packages/mds-geography-service/tests/index.spec.ts
packages/mds-ingest-service/tests/index.spec.ts
packages/mds-jurisdiction-service/tests/index.spec.ts
packages/mds-policy-service/tests/index.spec.ts

Initialize/shutdown repositories so tests are independent (i.e. `describe.only` does not hang)

Add beforeAll/initialize; afterAll/shutdown to repository tests

---

packages/mds-attachment-service/package.json
packages/mds-audit-service/package.json
packages/mds-geography-service/package.json
packages/mds-ingest-service/package.json
packages/mds-jurisdiction-service/package.json
packages/mds-policy-service/package.json

Drop schema before unit tests to prevent failure on multiple test runs (for example, revert migrations with existing data).

Drop schema before running unit tests

---

packages/mds-types/index.ts

Resolve build errors caused by recent changes to `@mds-core/mds-types`. @BigIdeas Please check these out. I fixed the build errors, but I need you to make sure I didn't alter the spirit/intent of your original changes.

Fix build errors caused by RateRule/RatePolicy

---

packages/mds-cache/redis/index.ts
packages/mds-cache/tests/redis.spec.ts

*[allow you to delete a range of items by score from a sorted set]*
Humans: Sorted sets have a score, we’re using “time” to sort items. This lets you “remove all items between (begining-of-time) and 8-hours ago”

adds zremrangebyscore to mds-cache

---

packages/mds-schema-validators/validators.ts
packages/mds-types/index.ts

PR #476 updated the policy and rule typedefs to allow for rates to be applied to any type of rule. This PR completes that work by updating the policy and rule validation schemas accordingly.

Update policy and rule validation schemas to allow rate properties

---

packages/mds-db/client.ts
packages/mds-db/schema.ts

Remove the final vestiges of `mds-db`'s usage of `PG_MIGRATIONS` for legacy side-effect style migrations. All migrations are now managed at startup by the new service pods.

Remove remaining mds-db migration code

---

Jenkinsfile
packages/mds-web-sockets/ws-server.ts

Need to ensure that builds are also successful in PR testing.
Additionally, fixes usage of `new Promise` that resolves `void` as a result of [TS 4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/)

need to also test ability to build in PR pipeline builds, fix void promise change

---

packages/mds-service-helpers/client/index.ts
packages/mds-service-helpers/tests/index.spec.ts

Adds isError helper, for all your error handling needs.

[mds-service-helpers] Add isError helper

---

packages/mds-service-helpers/@types/index.ts

This PR adds a new SerializedBuffers type, which will take any input type, and recursively traverse the type to transform any `Buffer` types to the serialized version, `ReturnType<Buffer['toJSON']>`. I found while decoupling attachments logic from mds-audit, that when receiving a Buffer in RPC-TS, it is the JSON serialized version, as opposed to a proper JS Buffer. This aims to allow ServiceDefinitions to be passed in with the proper, deserialized types, while retaining the serialized nature of buffers when receiving them as either the client or the provider, so they can then be properly parsed.
Example:
```typescript
type Foo = { x: string; y: { z: Buffer } }
type SerializedFoo = SerializedBuffers<Foo>
const example: Foo = { x: 'hi', y: { z: Buffer.from([1, 2, 3]) } }
const …
```

[mds-service-helpers] Add SerializedBuffers to ServiceProvider inputs, and ServiceClient outputs.

---

.bulldozer.yml

As the amount of contributors scales up, and the size of mds-core grows, there's a need to automate more portions of the PR process. This adds [Bulldozer](https://github.com/palantir/bulldozer) to the mds-core repo, which allows a PR creator to mark a PR as "ready to merge", and once requisite status-checks & approvals have come through, will automatically merge. Additionally, it will keep PRs up to date, so no longer will developers have to continuously hit the "update branch" button in Github.
To mark a PR as 'ready to merge', you can add the label `bulldozer-merge`, and Bulldozer will auto-merge upon all status checks & review requirements being passed. Additionally, you can mark a PR as 'keep updated' using the label `bulldozer-update`, and Bulldozer will automatically keep your PR …

Add bulldozer.yml

---

packages/mds-attachment-service/tests/index.spec.ts
packages/mds-audit/attachments.ts

Hotfix fixing something that shouldn't have gotten through the CI tests in the first place...
- mds-attachment-service (tests)

[mds-attachment-service] Remove unused import so CI/CD is happy

---

Jenkinsfile

Fixes two issues: dangling docker containers, and not catching test failures

exit immediately on any failure, move docker cleanup to exit function

---

packages/mds-cache/redis/index.ts
packages/mds-cache/tests/redis.spec.ts
packages/mds-types/index.ts

*[ExpireAt is powerful with Redis, but timestamps in MDS use Unix time in milliseconds]*
* mds-cache

Adds expiry for milliseconds, crucial for mds time

---

package.json
pnpm-lock.yaml

```
Running: "pnpm audit --json --audit-level=low"
Found 1 known vulnerability in 1830 dependencies (excluding 1556, 1561)
- https://npmjs.com/advisories/1623: Regular Expression Denial of Service (MODERATE)
- . > typedoc > marked@1.2.9
```
nothing really

Bump Typedoc version to resolve audit advisory

---

packages/mds-db/client.ts
packages/mds-db/package.json
pnpm-lock.yaml

If an API gets hit with a number of concurrent requests following a cold start, it's possible for all requests to try to establish a DB connection resulting in potential max connection errors. Use a simple locking mechanism to implement a semaphore around the connection caching.

Prevent connection exhaustion following client cold start

---

container-images/mds-attachment-service/Dockerfile

After upgrading to Node v15, I experienced issues generating images that mandate the installation of `sharp`.
```
npm ERR! Tracker "idealTree" already exists
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-05T20_32_49_925Z-debug.log
```
This looks like it is due to a change in Node v15 where npm is executed from the root of a container, and results in a failure. This is resolved by moving the installation to after we've created a `WORKDIR`.
- container-images/mds-attachment-service

[mds-attachment-service] Move sharp installation in Dockerfile

---

container-images/mds-audit/Dockerfile
package.json
pnpm-lock.yaml

`image` command for `mds-audit` is breaking Jenkins MDS Core (build/test/image). The installation of `sharp` is not longer required.

Fix mds-audit image; sharp is no longer required

---

packages/mds-collector-api/handlers/write-schema-messages.ts
packages/mds-collector-backend/@types/index.ts
packages/mds-collector-backend/client/index.ts
packages/mds-collector-backend/service/provider.ts
packages/mds-collector-backend/tests/service.spec.ts

The `NonEmptyArray` type is good in theory, but awkward in practice.

Relax type constraint on Collector service method

---

packages/mds-attachment-service/service/helpers/index.ts

We were experiencing issues in a deployed environment where we were unable to upload attachments to S3 due to an `Invalid Credentials` error. I hooked up to the cluster with Okteto, and discovered that the credential fetching code was doing WeirdThings, and basically wiping out the *good* credentials that were being loaded in automagically from the EC2's IAM roles. This PR removes that code. This PR has been tested in a remote cluster while using Okteto.
- mds-attachment-service

[mds-attachment-service] Remove strange S3 credential management

---

packages/mds-transaction-service/repository/index.ts

Use shared alias for getTransactions' QueryBuilder & TypeORM Cursor Paginator. This resolves conflicting aliases between the libraries depending on runtime environment (would work in debug but not prod, or prod and not debug).
```
{
exception: { error: [Object] },
error: {
message: 'missing FROM-clause entry for table "transactionentity"',
length: 129,
name: 'QueryFailedError',
severity: 'ERROR',
code: '42P01',
position: '333',
file: 'parse_relation.c',
line: '3459',
routine: 'errorMissingRTE',
query: 'SELECT "o"."recorded" AS "o_recorded", "o"."id" AS "o_id", "o"."transaction_id" AS "o_transaction_id", "o"."provider_id" AS "o_provider_id", "o"."device_id" AS "o_device_id", "o"."timestamp" AS "o_timestamp", "o"."fee_type" AS "o_fee_type", "o"."amount" AS "o_amount", "o"."receipt" AS …
```

[mds-transaction-service] Create shared alias for both QueryBuilder & TypeORM Cursor Paginator

---

packages/mds-logger/index.ts
packages/mds-logger/tests/index.spec.ts

Since switching from `JSON.stringify()` to printing out JSON logs directly, we've been seeing shallow-depth printing that appears like: `{ a: 'a', b: { c: 'c', d: [Object] } }`. This isn't ideal, as oftentimes you want to see the full object. This PR makes it so mds-logger will print objects with infinite depth, which it was _technically_ doing before, albeit under the purview of `JSON.stringify()`, so I'm not concerned about any performance issues.
` a: 'a', b: { c: 'c', d: [Object] } }`
- mds-logger

[mds-logger] Add infinite logging depth for nested JSON

---

okteto.yml
packages/mds-attachment-service/service/manager.ts

Increases `mds-attachment-service` RPC request size limit.
Also updates the okteto config with some new required properties.
- mds-attachment-service

Increase attachment-service RPC request size

---

packages/mds-collector-backend/schema-validator.ts
packages/mds-collector-backend/tests/schema-validator.spec.ts

Facilitate more consistent error handling by wrapping raw JSON Schema validation errors from `ajv` in a standard `ValidationError` object. Now, it is sufficient to just have unit tests assert that a validation error is thrown when expected.

Use ValidationError to wrap raw ajv errors

---

packages/mds-logger/index.ts

Resolves an issue with the latest version of mds-logger that prevented it working in non-nodejs environments.
- mds-logger

[mds-logger] Verify that defaultOptions is available before use

---

packages/mds-agency/utils.ts

Extends lat/lng bounds that agency will accept to anything in the world except `0,0`
Resolves #576
- mds-agency

[mds-agency] Extend lat/lng bounds to allow anything in the world except 0,0. Resolves #576

---

packages/mds-schema-validators/v0_4_1/index.ts
packages/mds-types/index.ts
packages/mds-types/transformers/1_0_0_to_1_1_0/devices.ts
packages/mds-types/transformers/index.ts
pnpm-lock.yaml

Exports transformers & typedefs from the tippy-top level of `@mds-core/mds-types`.
Also fixes up the lockfile :)
`Cannot find module '@mds-core/mds-types/transformers/@types' from '../../node_modules/.pnpm/@mds-core+mds-schema-validators/node_modules/@mds-core/mds-schema-validators/dist/v0_4_1/index.js'`
- mds-types
- mds-schema-validators

[mds-types] [mds-schema-validators] Clean up @mds-core/mds-types/transformers types

---

packages/mds-agency/api.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-schema-validators/trip-metadata-validators.ts

Relaxes the TripMetadata schema a bit, and adds HTTP PATCH support (albeit, doing the exact same thing as POST, for now). I kept the traditionally required properties commented out for posterity.
TOO MUCH STRICTNESS!
- mds-agency
- mds-schema-validators

[mds-agency] [mds-schema-validators] Relax TripMetadata schema (for now), add HTTP PATCH support

---

container-images/mds-compliance-api/package.json

Fixes `mds-compliance-api` container image being built with old incorrect name "mds-compliance".

update image build command with correct package name

---

packages/mds-agency/request-handlers.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-agency/types.ts

*[mds-agency would crash when `{data:}` was missing from post body]*
*[mds-agency]*

vehicle telemetry now handles missing data from post-body

---

packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-agency/utils.ts

*[telemetry gps validation should ignore optional attributes when values are null]*
*[mds-agency]*

gps optional attributes when null should be ignored

---

packages/mds-stream/index.ts

`mds-stream` wasn't passing along the `REDIS_PASS` environment variable, so it was unable to connect to a password protected redis. This PR fixes that!
S
'redis error ReplyError: Ready check failed: NOAUTH Authentication required.'
- mds-stream

[mds-stream] Use REDIS_PASS in mds-stream redis client

---

package.json

There was a vulnerability in `hosted-git-info` posted yesterday, and this package is a downstream dependency of some of our eslint plugins. It appears that the version which we use is actually up to date, though, according to [this GitHub issue](https://github.com/benmosher/eslint-plugin-import/issues/2046), but they have yet to update the CVE. This PR ignores the advisory temporarily so CI/CD can pass.
- failing CI/CD
n/a

[dependencies] Ignore hosted-git-info audit advisory

---

package.json
packages/mds-agency/api.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-policy/api.ts
packages/mds-providers/index.ts

`mds-agency` had middleware which verified that any `provider_id` claims made in the token were considered 'known' providers, meaning they were enumerated within the `mds-providers` package. Because that package really mirrors what is currently considered a Provider by the OMF, and is not considering other modes of transportation, for ease of integration with non-micromobility providers, I have removed the requirement for a `provider_id` check in `mds-agency`. 
Some new provider traffic being bounced
- mds-agency

[mds-agency] Remove known provider_id check

---

packages/mds-stream/nats/codecs.ts

It seems like the `nats.js` library uses JS Getters for NATS messages, which results in issues with how we're trying to inherit all properties from a `Msg` and override `data`. Attempting to access vanilla `Msg` properties, such as `subject` from within a `processor` function results in an inability to access properties that appear to exist given the typedef. This PR makes it so we only pass `subject` and a decoded `data` property to our processors, so that we can access `subject` using the getter prior to the object being unbound. Gotta love it when the types lie to you. 
Being unable to access `subject` from processors.
- mds-stream

[mds-stream] Rework NATS Cb Signature

---

packages/mds-api-server/middleware/request-logging.ts
packages/mds-logger/index.ts

Sometimes when triaging issues, it's useful to see request bodies, parameters, queries, etc... This PR adds a new middleware which can be toggled by a `REQUEST_DEBUG` env var.
- all APIs

[mds-api-server] [mds-logger] Add Debug Express Logger

---

packages/mds-types/event.ts
packages/mds-types/event_states_maps.ts

Removes a bad copy-pasta from the initial implementation of the TNC State Machine, and brings it into conformance with the MDS Standard.
- spec/code discontinuity
- mds-types

[mds-types] Remove maintenance from TNC State Machine

---

packages/mds-types/trip.ts

This PR allows for foreign-key type injection to the TripMetadata type, in addition to some base required properties. It also sets many properties which were previously required to Optional.
- mds-types

[mds-types] Make MDS TripMetadata extensible

---

package.json
packages/mds-utils/utils.ts

This function was written before the advent of const assertions in TypeScript. Allow the function to work with readonly arrays.
- mds-utils

Allow randomElement function to operate on const arrays

---

package.json

Ignores [Advisory 1753](https://www.npmjs.com/advisories/1753) which there is a Github issue to fix in [lerna](https://github.com/lerna/lerna/issues/2925).
- CI/CD failure due to advisory

Ignore advisory 1753 from Lerna

---

packages/mds-agency/request-handlers.ts

@avatarneil Evan requires that the `recorded` property be present for watermarking to function properly. I don't see any issues with just appending it here. Thoughts?

Data pipeline needs trip metadata recorded property for watermarking.

---

packages/mds-agency-cache/index.ts
packages/mds-agency/request-handlers.ts

There's no need to persist trip metadata to the redis cache, and in fact, this could blow up the number of entries in the redis cache over time. This PR makes it so we no longer persist TripMetadata to the redis cache, and solely write it to the stream.
- mds-agency

[mds-agency] Remove TripMetadata cache writes

---

packages/mds-agency/request-handlers.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-agency/types.ts
packages/mds-api-server/@types/index.ts

This PR started off as an attempt to optimize checking if a `device_id` was valid during bulk Telemetry POSTs, but ended up changing a lot more than that.
Previously, we were doing a check on each device referenced in a bulk telemetry POST to verify that it was valid for that provider, which was a worst-case `O(N)` check per-device, where `N=total number of devices for a provider`. For the entirety of the POST, this was `O(N * M)` where `M` is the number of devices included in the bulk telemetry POST. Pretty bad performance-wise. This PR changes things, such that instead of maintaining an array of all of the providers' `device_ids` in memory, we maintain a `Set` which contains them. To generate the `Set` in the first place takes `O(N)` time, but then each individual check is `O(1)`, so …

[mds-agency] Fix POST telemetry response in accordance with 1.0 spec, improve performance

---

packages/mds-agency/package.json
packages/mds-agency/request-handlers.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-agency/types.ts
packages/mds-agency/utils.ts
packages/mds-db/devices.ts
packages/mds-ingest-service/index.ts
packages/mds-ingest-service/service/validators.ts
packages/mds-types/device.ts
pnpm-lock.yaml

Whew, this was a bit of an adventure. Parsing validation errors from AJV into a format that conforms with the MDS Agency spec was a bit of a journey, but I think this ought to work reasonably well. I adjusted the tests a bit because the error messages we previously sent were, while conformant with the spec, not necessary to continue emitting (e.g namely the data in `error_details`). I also removed one piece of validation which mandated that the device `year` property was between 1980 & 2020 (fun future bug which could hypothetically have been causing issues if Providers actually sent the `year` property in production).
Ideally, the `agencyErrorParser` will be helpful when parsing validation errors for events, though I suspect that given the odd error handling for the Telemetry endpoint it …

[mds-agency] Switch Device validation to AJV

---

packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-agency/utils.ts

This PR removes some strict validation for model year in the device registration flow. It's targetted at the `support/mds-0.4.1` branch, which is what is currently deployed to 0.4.1 environments.
Being unable to register vehicles >2020
- mds-agency

[mds-agency] [LEGACY SUPPORT] Accept device registration for devices with any integer year

---

.prettierrc.json
package.json
packages/mds-agency/api.ts
packages/mds-agency/handlers/create-telemetry.ts
packages/mds-agency/request-handlers.ts
packages/mds-agency/tests/integration-tests.spec.ts
packages/mds-agency/types.ts
packages/mds-agency/utils.ts
packages/mds-ingest-service/@types/index.ts
packages/mds-ingest-service/repository/entities/telemetry-entity.ts
packages/mds-ingest-service/repository/mappers/telemetry-mappers.ts
packages/mds-ingest-service/repository/migrations/1624574421590-AddTelemetryStopIdHdopSatellitesColumns.ts
packages/mds-ingest-service/repository/migrations/index.ts
packages/mds-ingest-service/service/validators.ts
packages/mds-ingest-service/tests/index.spec.ts
packages/mds-types/telemetry.ts
pnpm-lock.yaml

As with many of my PRs recently, this started with the simple task of adding an AJV validator for Telemetry, but then I soon realized that there were discontinuities with the MDS spec...
- Switches mds-agency to using AJV for telemetry schema validation, nukes `badTelemetry()` from orbit
- Adds three new nullable columns to `Telemetry`: `hdop`, `satellites`, and `stop_id`.
- For bonus points, adds a new prettier plugin for import organizing :)
- spec discontinuities
- mds-agency
- mds-ingest-service
- mds-types

[mds-agency] Switch Telemetry Validation to AJV, fix spec discontinuities

---

packages/mds-ingest-service/repository/entities/event-annotation-entity.ts
packages/mds-ingest-service/service/validators.ts
packages/mds-schema-validators/validators.ts

Some minor cleanup that didn't make it into https://github.com/lacuna-tech/mds-core/pull/640 before I merged:
* Decouple the `EventAnnotationEntity` and `EventAnotationEntityModel`
* Reuse some schema definitions from mds-schema-validators
There's opportunity for lots more cleanup across packages in consolidating our schema definitions but I'll hold off on that in favor of fixing with AJV.

Address some comments from PR #640

---

packages/mds-ingest-service/repository/migrations/1625676583247-AddEventsTripIdTimestampIndex.ts
packages/mds-ingest-service/repository/migrations/index.ts

Adds missing migration to `migrations/index.ts`
- migration existing but not being run
- mds-ingest-service

[mds-ingest-service] Add missing migration to migrations/index.ts
